- README.md
- components/info.vue
- index.js
- package.json
- router.js
- store.js
@collymore Hi, Luke! I prepare first pull. Please, approve.
Have a nice day!
> Skeleton for the  PayPal integration.

- README.md
\+ @collymore additional doc fix
> Doc fix: about install extension

- components/PaymentPaypal.vue
- index.js
- package.json
- pages/PageExample.vue
- router.js
Added router for improve development process. For using need uncomment it.
\+ @collymore
> PaymentPaypal component.

- components/Button.vue
- components/PaymentPaypal.vue
- pages/PageExample.vue
@collymore  Hi, Luke. Added first preview for PayPal button.
> Added PayPal button.

- components/Button.vue
- index.js
- router.js
@collymore The Paypal server-side integration is ready.
> Order execution to paypal with checkout transactions data.

- README.md
> Updated installation instruction in README.md

- components/Button.vue
Completed fix for stable place order after payment execute.
> Auto pass terms validation.

- index.js
This change seems to fix the compatibility issues with the Paypal Checkout Library
> Fix issue #15

- index.js
> Hide/show order button instead global event to core.

- components/Button.vue
> Access to config from vuex store.

- README.md
- components/Button.vue
> The grand_total computed.

- index.js
> Use vsfpaypal as a payment code.

- hooks/beforeRegistration.ts
\+ @collymore 
The Payment method registration without EventBus.
> Paypal registration with use watch state of Vuex storage.

- components/Button.vue
- store/actions.ts
\+ @collymore 
And create test order with paypal method.
> Moved fetch logic of execute payment to store action.

- components/Button.vue
- hooks/beforeRegistration.ts
> Moved load the paypal api external script to beforeRegistration hook.

- README.md
https://github.com/DivanteLtd/vue-storefront/blob/5cad3aa0496e03fe557b1beae46ebe068b073393/config/default.json#L204
\+ @collymore
> Cart synchronize by default start from VSF 1.6.0

- hooks/beforeRegistration.ts
> Update registration hook to 1.8.0 version

- components/Button.vue
Fixed paypal button component from Vsf v1.8
> Fixed button component for Vsf 1.8.x

- components/Button.vue
Accordance by
https://github.com/DivanteLtd/vue-storefront/blob/40840ecbe5b1ffa9e83e72cf20f41b3448bb874c/core/store/package.json#L2
+ @ananth-iyer
> Corrected by core space name

- api/paypal/index.js
Backward compatibility for old version, `0.1.x` branch.
\+ @collymore
> Added api backward compatibility.

- README.md
> Installation.

- api/paypal/index.js
> Check on create payment errors.

- index.js
\+ @collymore for 0.1.x legacy version.
> Fixed payment code

- components/Button.vue
See update notes at https://docs.vuestorefront.io/guide/upgrade-notes/#_1-8-1-9
> @vue-storefront/store package has been depreciated

- README.md
I couldn't get it working with data, it was always cash on delivery
> Use computed instead of data for paymentMethod

- components/Button.vue
> #91 Rafactor by use async/await.

- components/Button.vue
- package.json
@collymore 
Fixed compatibility for 1.10.0 release 
https://github.com/DivanteLtd/vue-storefront/releases/tag/v1.10.0
> Cart totals

- components/Button.vue
> #103 Setup currency code for purchase.

- CHANGELOG.md
- index.ts
- package.json
\+ @collymore Published the new version with tag `v0.7.0`
> #107 Updated the module signatura - compatibility with VSF 1.10.x.

- CHANGELOG.md
- components/Button.vue
- package.json
> #114 Added support the style attribute for any buttons customizations.

- CHANGELOG.md
- package.json
> Bump version to v1.0.4.

- README.md
Removed notice about `region_code` because module tested for all region code, not only for US.
Other only a VSF core related issues with create order instead of region with US code.
\+ @collymore
> Updated readme with tested releases.

- CHANGELOG.md
- README.md
- package.json
> Capybara integration

- README.md
- components/PaypalButton.js
> #102 Support terms and conditions. Added translation. Small refactoring.

- API/paypal/index.js
- CHANGELOG.md
- package.json
I think this commit could be useful to debug (especially in a live environment).
> Added error log informations

- README.md
Added important notice about the local.json configuration.
> Added IMPORTANT section

- hooks/afterRegistration.ts
> Replace deprecated Vue.prototype.$bus with EventBus
